/**
 * Build-time manifest signing.
 *
 * Generates an Ed25519 keypair via @noble/curves:
 *   - private key -> keys/ (gitignored; created only here, never committed)
 *   - signs sha256-stamped exhibit spans from corpus/
 *   - writes public/evidence/manifest.json (public key + signature ONLY)
 *   - writes src/generated/manifest.ts so the bundle imports the signed
 *     manifest directly — zero network fetches at runtime.
 *
 * Run: npm run build:manifest
 */

import { createHash } from 'node:crypto'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { ed25519 } from '@noble/curves/ed25519.js'
import { parseExhibitSource } from '../src/domain/exhibitParse.ts'
import { manifestSigningPayload } from '../src/domain/manifestPayload.ts'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const CORPUS_DIR = path.join(ROOT, 'corpus', 'exhibits')
const PUBLIC_DIR = path.join(ROOT, 'public', 'evidence')
const GENERATED_DIR = path.join(ROOT, 'src', 'generated')
const KEYS_DIR = path.join(ROOT, 'keys')

function sha256Hex(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

function toHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('hex')
}

async function loadExhibits() {
  const files = (await readdir(CORPUS_DIR)).filter((f) => f.endsWith('.txt')).sort()
  if (files.length < 12 || files.length > 15) {
    throw new Error(`expected 12-15 exhibits, found ${files.length}`)
  }
  const exhibits = []
  for (const file of files) {
    const source = await readFile(path.join(CORPUS_DIR, file), 'utf8')
    const parsed = parseExhibitSource(source)
    exhibits.push({
      id: parsed.id,
      title: parsed.title,
      spans: parsed.spans.map((s) => ({
        span_id: s.span_id,
        text: s.text,
        sha256: sha256Hex(s.text)
      }))
    })
  }
  exhibits.sort((a, b) => a.id.localeCompare(b.id))

  // Sanity: exhibit ids must be unique and span ids unique within an exhibit.
  const ids = new Set(exhibits.map((e) => e.id))
  if (ids.size !== exhibits.length) throw new Error('duplicate exhibit ids in corpus')
  return exhibits
}

const exhibits = await loadExhibits()

// Keypair. Private material touches disk ONLY inside gitignored keys/.
const privateKey = ed25519.utils.randomPrivateKey()
const publicKey = ed25519.getPublicKey(privateKey)
// Signature covers the manifest OF EXHIBIT HASHES (ids, titles, span ids,
// recorded sha256s). Span text binds via the per-span hash recompute at
// runtime — flipping text quarantines surgically; flipping structure or
// hashes breaks the signature and quarantines everything.
const payload = manifestSigningPayload(exhibits)
const signature = ed25519.sign(payload, privateKey)

await mkdir(KEYS_DIR, { recursive: true })
await writeFile(
  path.join(KEYS_DIR, 'manifest-signing.key'),
  toHex(privateKey) + '\n',
  { mode: 0o600 }
)

const manifest = {
  format: 'evidence-desk-manifest/v1',
  algorithm: 'ed25519',
  exhibits,
  publicKey: toHex(publicKey),
  signature: toHex(signature)
}

await mkdir(PUBLIC_DIR, { recursive: true })
await writeFile(
  path.join(PUBLIC_DIR, 'manifest.json'),
  JSON.stringify(manifest, null, 2) + '\n'
)

await mkdir(GENERATED_DIR, { recursive: true })
await writeFile(
  path.join(GENERATED_DIR, 'manifest.ts'),
  `// AUTO-GENERATED by scripts/build-manifest.mts — do not edit by hand.
// Contains PUBLIC key material only. The private signing key lives in
// gitignored keys/ and never enters the bundle or source control.
import type { EvidenceManifest } from '../domain/types.ts'

export const MANIFEST: EvidenceManifest = ${JSON.stringify(manifest, null, 2)}
`
)

const manifestHash = createHash('sha256').update(JSON.stringify(manifest)).digest('hex')
console.log(
  `manifest: ${exhibits.length} exhibits, ` +
    `${exhibits.reduce((n, e) => n + e.spans.length, 0)} spans signed`
)
console.log(`manifest sha256: ${manifestHash}`)
console.log(`public key: ${toHex(publicKey)}`)
console.log('private key written to keys/manifest-signing.key (gitignored)')
